---

services:
  gitlab:
    image: gitlab/gitlab-ce:17.7.1-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.barrylabs.local'
        pages_external_url 'https://pages.gitlab.barrylabs.local'
        registry_external_url 'https://registry.gitlab.barrylabs.local'
        nginx['redirect_http_to_https'] = true

    networks:
      gitlab:
        aliases:
          - gitlab.barrylabs.local
          - registry.gitlab.barrylabs.local
          - gitlab
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    
    shm_size: '256m'   
    
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - ./certs:/etc/gitlab/ssl

  gitlab-runner:
    depends_on:
      - gitlab
    image: gitlab/gitlab-runner:v17.6.1
    container_name: gitlab-runner
    restart: always
    networks:
      gitlab:
        aliases:
          - gitlab-runner
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:

networks:
  gitlab:
