---

- name: Install docker
  hosts: all
  become: true

  roles:
    - geerlingguy.docker

  tasks:

    - name: Add user in docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Create docker compose directory
      ansible.builtin.file:
        path: /home/ubuntu/minio
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy docker compose files
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: /home/ubuntu/minio/{{ item }}
        mode: '0644'
        owner: ubuntu
        group: ubuntu
      loop:
        - compose.yml
        - .env

    - name: Start docker compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/minio
        state: present
